version: '3'

volumes:
  my-db: 
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - scc4-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - mysql
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testescc4?createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: 
      - scc4-network
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - './frontend:/usr/src/app'
      ports: 
        - '4200:4200'
      depends_on: 
        - mysql
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
      networks: 
      - scc4-network
networks: 
  scc4-network:
    driver: bridge